    export const interiors = [
        { id: 1, name: "· UI REDESIGN" , stu: "양성우"},
        { id: 2, name: "· UI REDESIGN" , stu: "양성우"},
        { id: 3, name: "· 프로젝트 제목" , stu: "양성우"},
        { id: 4, name: "· 구찌 오스테리아 리디자인" , stu: "양성우"},
        { id: 5, name: "· 맥도날드 앱 리디자인" , stu: "양성우"},
        { id: 6, name: "· 팀 프로젝트" , stu: "양성우"},
        { id: 7, name: "· 프로젝트 제목" , stu: "양성우"},
        { id: 8, name: "· UI REDESIGN" , stu: "양성우"},
        { id: 9, name: "· 프로젝트 제목" , stu: "양성우"},
        { id: 10, name: "· 프로젝트 제목" , stu: "양성우"},
        { id: 11, name: "· 프로젝트 제목" , stu: "양성우"},
        { id: 12, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 13, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 14, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 15, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 16, name: "· WEB REDESIGN" , stu: "양성우"},
        { id: 17, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 18, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 19, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 20, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 21, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 22, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 23, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 24, name: "· 팀 프로젝트" , stu: "양성우"},
        { id: 25, name: "· 팀 프로젝트" , stu: "양성우"},
        { id: 26, name: "· 팀 프로젝트" , stu: "양성우"},
        { id: 27, name: "· 팀 프로젝트" , stu: "양성우"},
        { id: 28, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 29, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 30, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 31, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 32, name: "· UI/UX REDESIGN" , stu: "양성우"},
        { id: 33, name: "· 팀 프로젝트" , stu: "양성우"},
        { id: 34, name: "· 팀 프로젝트" , stu: "양성우"},
        { id: 35, name: "· 팀 프로젝트" , stu: "이름"},
        { id: 36, name: "· 웹 사이트 리디자인" , stu: "양성우"},
        { id: 37, name: "· 웹 사이트 리디자인" , stu: "양성우"},
        { id: 38, name: "· 웹 사이트 리디자인" , stu: "양성우"},
        { id: 39, name: "· 웹 사이트 리디자인" , stu: "양성우" },
        { id: 40, name: "· 웹 사이트 리디자인", stu: "양성우" },
    ];
